[package]
name = "millau-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
hex-literal = "0.3"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
libsecp256k1 = { version = "0.7", optional = true, default-features = false, features = ["hmac"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }

# Bridge dependencies

bp-header-chain = { path = "../../../primitives/header-chain", default-features = false }
bp-message-dispatch = { path = "../../../primitives/message-dispatch", default-features = false }
bp-messages = { path = "../../../primitives/messages", default-features = false }
bp-millau = { path = "../../../primitives/chain-millau", default-features = false }
bp-rialto = { path = "../../../primitives/chain-rialto", default-features = false }
bp-runtime = { path = "../../../primitives/runtime", default-features = false }
bp-westend = { path = "../../../primitives/chain-westend", default-features = false }
bridge-runtime-common = { path = "../../runtime-common", default-features = false }
pallet-bridge-dispatch = { path = "../../../modules/dispatch", default-features = false }
pallet-bridge-grandpa = { path = "../../../modules/grandpa", default-features = false }
pallet-bridge-messages = { path = "../../../modules/messages", default-features = false }
pallet-bridge-token-swap = { path = "../../../modules/token-swap", default-features = false }
pallet-shift-session-manager = { path = "../../../modules/shift-session-manager", default-features = false }

# Substrate Dependencies

beefy-primitives = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
frame-benchmarking = { git = "https://github.com/koute/substrate", default-features = false, optional = true , branch = "master_check_if_madvise_works" }
frame-executive = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
frame-support = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
frame-system = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
frame-system-rpc-runtime-api = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-aura = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-balances = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-beefy = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-beefy-mmr = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-grandpa = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-mmr = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-randomness-collective-flip = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-session = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-sudo = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-timestamp = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-transaction-payment = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-api = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-block-builder = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-consensus-aura = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-core = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-finality-grandpa = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-inherents = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-mmr-primitives = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-offchain = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-runtime = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-session = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-std = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-transaction-pool = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-trie = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }
sp-version = { git = "https://github.com/koute/substrate", default-features = false , branch = "master_check_if_madvise_works" }

[dev-dependencies]
bridge-runtime-common = { path = "../../runtime-common", features = ["integrity-test"] }
static_assertions = "1.1"

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/koute/substrate", branch = "master_check_if_madvise_works" }

[features]
default = ["std"]
std = [
	"beefy-primitives/std",
	"bp-header-chain/std",
	"bp-message-dispatch/std",
	"bp-messages/std",
	"bp-millau/std",
	"bp-rialto/std",
	"bp-runtime/std",
	"bp-westend/std",
	"bridge-runtime-common/std",
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-beefy/std",
	"pallet-beefy-mmr/std",
	"pallet-bridge-dispatch/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-bridge-token-swap/std",
	"pallet-grandpa/std",
	"pallet-mmr/std",
	"pallet-randomness-collective-flip/std",
	"pallet-session/std",
	"pallet-shift-session-manager/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"sp-inherents/std",
	"sp-mmr-primitives/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-trie/std",
	"sp-version/std",
]
runtime-benchmarks = [
	"bridge-runtime-common/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"libsecp256k1",
	"pallet-bridge-messages/runtime-benchmarks",
	"pallet-bridge-token-swap/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
